org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -XX:+UseG1GC
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=true

android.useAndroidX=true
android.enableJetifier=true
android.useFullClasspathForDexingTransform=true
org.gradle.warning.mode=none

# gradle.properties
android.aapt2FromMavenOverride=/data/data/com.termux/files/usr/bin/aapt2